language: node_js
node_js:
  - "stable"
script:
  - yarn test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: f6ab5aaca6b12f0b2b7d77d881ebec91b3de25cd
  keep_history: true
  on:
    branch: master