language: node_js
node_js:
  - "11.10.1"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run lint
  - yarn run test
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master
