language: node_js
node_js:
  - "stable"
script:
  - yarn test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: d3da291dcc4ecd5e7ef6373356d714cb49814320
  keep_history: true
  on:
    branch: master
