language: node_js
node_js:
  - "stable"
script:
  - yarn test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $3e91cebc2b732904d4c36315cf486a28efb7a445
  keep_history: true
  on:
    branch: master