language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run test
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: d3da291dcc4ecd5e7ef6373356d714cb49814320
  local_dir: build
  on:
    branch: master
